# Site settings
title: histograph
email: histograph@cvce.eu
url: http://cvceeu-dh.github.io/histograph
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: /histograph

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-white: '#fff'
  primary-dark: '#151515'
  links: '#219ab3'

# Footer settings
footer: CVCE

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap


# Build settings
markdown: kramdown
permalink: pretty

# collections
collections:
- narrative

# google tracking
google_analytics: UA-73228039-1
