version: '3.7'
services:
  neo4j:
    image: neo4j:3.5
    environment: 
      NEO4J_AUTH: neo4j/neo4jpwd
      # Memory configuration tweaks:
      # NEO4J_dbms_memory_heap_initial__size=12000m
      # NEO4J_dbms_memory_heap_max__size=12000m
      # NEO4J_dbms_memory_pagecache_size=12100m
    volumes:
      - ./data/neo4j:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  histograph:
    restart: always
    image: c2dhunilu/histograph
    environment:
      NODE_ENV: production
      PORT: 8000
    depends_on:
      - neo4j
    volumes:
      - ./data/histograph-contents:/histograph/contents
      - ./config/histograph.js:/histograph/settings.js
  nginx:
    restart: always
    image: nginx:1.17-alpine
    ports:
      - 80:80
      - 443:443
    depends_on:
      - histograph
      - iipsrv
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    command: [nginx-debug, '-g', 'daemon off;']
  iipsrv:
    restart: always
    image: c2dhunilu/iipsrv
    volumes:
      - ./data/iipsrv_images:/data/images
  histograph_init:
    restart: on-failure
    image: c2dhunilu/histograph
    entrypoint: /bin/sh -c "node scripts/init.js && node scripts/manage.js --task entity.jaccard --entity person"
    depends_on:
      - neo4j
    volumes:
      - ./data/histograph-contents:/histograph/contents
      - ./config/histograph.js:/histograph/settings.js
